//
//  TBApiHTTPRequest.swift
//  
//
//  Created by Johannes Kinzig on 06.09.24.
//

import Foundation
import OSLog

public class TBHTTPRequest {
    
    // MARK: - Properties
    var httpClient: SimpleHTTPClient
    private(set) var apiErrorHandler: ((TBAppError) -> Void)? = nil
    private(set) var systemErrorHandler: ((TBSystemError) -> Void)? = nil
    let logger: Logger?
    
    // MARK: - Initialization

    /// Initializes a new TBHTTPRequest with a custom URLSession handler, a request timeout, and an optional logger.
    /// - Parameters:
    ///   - httpSessionHandler: The session handler used to perform network requests (useful for dependency injection and testing).
    ///   - requestTimeout: The timeout interval, in seconds, for HTTP requests created by this client.
    ///   - logger: Optional OSLog Logger used to record diagnostic messages. If nil, logging is disabled.
    init(httpSessionHandler: URLSessionProtocol, requestTimeout: TimeInterval, logger: Logger? = nil) {
        httpClient = SimpleHTTPClient(sessionHandler: httpSessionHandler, requestTimeout: requestTimeout, logger: logger)
        self.logger = logger
    }
    
    // MARK: - Implementation
    /**
     Register an error handler
     
     Register two error handlers:
     + one which handles errors generated by the API (e.g. reponding with an error message)
     + the other one handles system errors, such as a failed HTTP request because of a subsystem failure (e.g. host unreachable, domain resolution fails, etc.)
     
     - Parameter apiErrorHandler: called when the API responds with an error, takes the server-provided ``TBAppError``
     - Parameter systemErrorHandler: called when the HTTP request fails locally, takes a ``TBSystemError``
     */
    public func registerErrorHandler(apiErrorHandler: ((TBAppError) -> Void)? = nil, systemErrorHandler: ((TBSystemError) -> Void)? = nil) {
        self.apiErrorHandler = apiErrorHandler
        self.systemErrorHandler = systemErrorHandler
    }
    
    /**
     TB API request simplifying each http call
     - Parameter fromEndpoint: Specify endpoint by giving the endpoint URL als 'TBApiEndpoints conforming protocol type'
     - Parameter usingMethod: Give the desired HTTP method, default: .post
     - Parameter withPayload: HTTP request payload given as Dictionary<String, Any>
     - Parameter authData: Authentication data
     - Parameter expectedTBResponseType: expected TB Data Model instance Type
     - Parameter successHandler: function to run in case of success
     */
    internal func tbApiRequest(fromEndpoint endpointURL: String,
                              usingMethod httpMethod: SupportedHTTPMethods = .post,
                              withPayload payload: Dictionary<String, Any>? = nil,
                              authToken authData: AuthLogin? = nil,
                               expectedTBResponseType responseType: any TBDataModel.Type,
                               successHandler: @escaping (any TBDataModel) -> Void)
    -> Void {
        var tbheaders = ["Content-Type": "application/json", "Accept": "application/json"]
        if let token = authData?.token { tbheaders["x-authorization"] = "Bearer \(token)" }
        httpClient.doHttpRequest(from: endpointURL, usingMethod: httpMethod, withhttpHeaders: tbheaders, withPayload: payload, expectedTBResponseType: responseType) { result in
            switch result {
            case .success(let responseObject):
                successHandler(responseObject)
            case .failure(let error):
                switch error {
                case .api(let apiError):
                    self.apiErrorHandler?(apiError)
                    self.logger?.error("TBRESTClientLib (serverside) Error Message: \(apiError) - \(apiError.localizedDescription)")
                case .system(let systemError):
                    self.systemErrorHandler?(systemError)
                    self.logger?.error("TBRESTClientLib (system) Error Message: \(systemError) - \(systemError.localizedDescription)")
                }
            }
        }
    }
}
