//
//  TBApiHTTPRequest.swift
//  
//
//  Created by Johannes Kinzig on 06.09.24.
//

import Foundation
import OSLog

public class TBHTTPRequest {
    
    // MARK: - Properties
    var httpClient: SimpleHTTPClient
    private(set) var apiErrorHandler: ((TBAppError) -> Void)? = nil
    private(set) var systemErrorHandler: ((TBHTTPClientRequestError) -> Void)? = nil
    let logger: Logger?
    
    // MARK: - Initialization
    init(httpSessionHandler: URLSessionProtocol, logger: Logger? = nil) {
        httpClient = SimpleHTTPClient(sessionHandler: httpSessionHandler,  logger: logger)
        self.logger = logger
    }
    
    // MARK: - Implementation
    /**
     Register an error handler
     
     Register two error handlers:
     + one which handles errors generated by the API (e.g. reponding with an error message)
     + the other one handles system errors, such as a failed HTTP request because of a subsystem failure (e.g. host unreachable, domain resolution fails, etc.)
     
     - Parameter apiErrorHandler: called when the API responds with an error
     - Parameter systemErrorHandler: called when the HTTP request fails
     */
    public func registerErrorHandler(apiErrorHandler: ((TBAppError) -> Void)? = nil, systemErrorHandler: ((TBHTTPClientRequestError) -> Void)? = nil) {
        self.apiErrorHandler = apiErrorHandler
        self.systemErrorHandler = systemErrorHandler
    }
    
    /**
     TB API request simplifying each http call
     - Parameter fromEndpoint: Specify endpoint by giving the endpoint URL als 'TBApiEndpoints conforming protocol type'
     - Parameter usingMethod: Give the desired HTTP method, default: .post
     - Parameter withPayload: HTTP request payload given as Dictionary<String, Any>
     - Parameter authData: Authentication data
     - Parameter expectedTBResponseType: expected TB Data Model instance Type
     - Parameter successHandler: function to run in case of success
     */
    internal func tbApiRequest(fromEndpoint endpointURL: String,
                              usingMethod httpMethod: SupportedHTTPMethods = .post,
                              withPayload payload: Dictionary<String, Any>? = nil,
                              authToken authData: AuthLogin? = nil,
                               expectedTBResponseType responseType: any TBDataModel.Type,
                               successHandler: @escaping (any TBDataModel) -> Void)
    -> Void {
        var tbheaders = ["Content-Type": "application/json", "Accept": "application/json"]
        if let token = authData?.token { tbheaders["x-authorization"] = "Bearer \(token)" }
        httpClient.doHttpRequest(from: endpointURL, usingMethod: httpMethod, withhttpHeaders: tbheaders, withPayload: payload, expectedTBResponseType: responseType) { result in
            switch result {
            case .success(let responseObject):
                successHandler(responseObject)
            case .failure(let error):
                if case TBHTTPClientRequestError.tbAppError(let apperror) = error {
                    // run registered app error handler
                    self.apiErrorHandler?(apperror)
                    self.logger?.error("TBRESTClientLib (serverside) Error Message: \(error) - \(error.localizedDescription)")
                } else if case TBHTTPClientRequestError.tbGenericError(let apperror) = error {
                    // run registered app error handler
                    self.apiErrorHandler?(apperror)
                    self.logger?.error("TBRESTClientLib (serverside) Error Message: \(error) - \(error.localizedDescription)")
                } else {
                    self.systemErrorHandler?(error)
                    self.logger?.error("TBRESTClientLib (system) Error Message: \(error) - \(error.localizedDescription)")
                }
            }
        }
    }
}
